homework 4 added (Working with Intents)
niyazm524/AndroidCourse-2k1s pull request #4
Opened 2019-10-21 21:57 UTC by niyazm524

2019-10-28 19:48 UTC, NailShaykhrazievItis requested changes

2019-10-28 19:48 UTC, NailShaykhrazievItis commented on app/src/main/AndroidManifest.xml
> +    <application android:allowBackup="true" android:icon="@mipmap/ic_launcher"
эээууу верни назад. Минус глаза

2019-10-28 19:48 UTC, NailShaykhrazievItis commented on app/src/main/java/ml/bimdev/baseapp/MainActivity.kt
> +    companion object {
лучше компаньон обжект в таком случае держать в конце класса. Я ж на паре расскаызывал. Ууууу не слушаете. УУУуууу. Никогда такого не было и вот опять

2019-10-28 19:48 UTC, NailShaykhrazievItis commented on app/src/main/java/ml/bimdev/baseapp/MainActivity.kt
> +                ShareCompat.IntentBuilder
ShareCompat - никогда с таким не сталкивался ну ок. Вот он прогресс

2019-10-28 19:48 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_email_receiver.xml
> +        app:layout_constraintEnd_toStartOf="@id/tv_right_body"
+id

2019-10-29 07:44 UTC, niyazm524 commented on app/src/main/java/ml/bimdev/baseapp/MainActivity.kt
> +                ShareCompat.IntentBuilder
красивая штука, и пользоваться удобно
гугл молодцы

2019-10-29 07:45 UTC, niyazm524 commented on app/src/main/java/ml/bimdev/baseapp/MainActivity.kt
> +    companion object {
(((уфф отвлекли..((

2019-10-29 07:45 UTC, niyazm524 commented on app/src/main/AndroidManifest.xml
> +    <application android:allowBackup="true" android:icon="@mipmap/ic_launcher"
ой, а это как так получилось

2019-10-29 21:25 UTC, NailShaykhrazievItis commented on app/src/main/java/ml/bimdev/baseapp/MainActivity.kt
> +                ShareCompat.IntentBuilder
Гугл молодцы. Каждый раз ору с этого. Иногда такую хрень делают

2019-10-29 21:25 UTC, NailShaykhrazievItis approved these changes

2019-10-29 21:25 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_email_receiver.xml
> +        app:layout_constraintStart_toEndOf="@+id/tv_left_body"
тут не нужно было

2019-11-09 17:21 UTC, closed without merging